session_name: vim_py
windows:
- focus: 'true'
  layout: main-vertical
  options:
    main-pane-width: 93
  start_directory: /home/seiv/dot/vim/bundle/vim-pythogen
  panes:
  - shell_command: vim -p plugin/pythogen.py ~/.vim/py_plugins_configs/pythogen.json .tmuxp.yaml ~/dot/vim/bundle/iv-commands/plugin/iv-commands.py
    focus: true
  - pane
  - tail -f /tmp/cc/*.log
  - tail -f /tmp/cc/pythogen/pythogen.log
  window_name: pythogen
